### PR TITLE
Adds proper installation of bash-autocomplete

### PR DESCRIPTION
**Pull request by codeZeilen**
This now requires pkg-config. It gracefully skips completion installation if not available, but this might be a somewhat strong requirement.

### CODE REVIEW

**Comment by krono** [comment]
install sh is going away. 
Can we incorporate this in swth itself?

**Comment by codeZeilen** [comment]
> install sh is going away.

I know :D Just didn't want to leave a wrong installation sitting around somewhere. 

> Can we incorporate this in swth itself?

Maybe as an `install-auto-complete` (or `_install-auto-complete`) command? Or is that too weird to have a "meta" command in the list?

**Comment by krono** [comment]
> > install sh is going away.
> 
> I know :D Just didn't want to leave a wrong installation sitting around somewhere.
good point

> 
> > Can we incorporate this in swth itself?
> 
> Maybe as an `install-auto-complete` (or `_install-auto-complete`) command? Or is that too weird to have a "meta" command in the list?

yes, i thought of something like that.

**Comment by codeZeilen** [comment]
:P One year later, I finally came around to move the changes around a bit.

**Comment by krono** [comment]
🕺

**Comment by krono** [comment]
YOLO

**Pull request merged**
