### PR TITLE
add oneside option

### PR DESCRIPTION
**Pull request by LinqLover**
Horizontally offset pages just hurt my eyes on my screen ... you might even argue that this should be the default unless print is set to true, but I'd leave that to you.

### CODE REVIEW

**Comment by krono** [comment]
Yeahh, I don't think so :)

**Comment by LinqLover** [comment]
:-(

Just to be sure, did you see that this patch does _not_ change the default appearance but just declares another option (`\DeclareOption{oneside}`)? Users of the document class _can_ opt-in to the oneside mode by doing

```tex
\documentclass[master,oneside]{swathesis}
```

I would like to use that for my thesis. I had hoped you would accept a patch for an optional variation to save me from maintaining a fork (and maybe some future students share my desire to not have binding correction on their screen). Sorry that the initial commit message was too imprecise.

**Comment by krono** [comment]
Do you want a detailed explanation?

**Comment by LinqLover** [comment]
If it's not too much effort, yes :D I'm mainly submitting PRs because I hope they can benefit others. If I understand the scope of this repository better, I don't need to do disturb anybody :)

**Comment by krono** [comment]
Hi sorry, I did not get to it.
Just step by if you have time for a chat.
Anyway, doing `\KOMAoption{twoside}{off}` or even `\KOMAoption{twoside}{semi}` can achive what you want on per-document basis :)

**Comment by LinqLover** [comment]
Sorry for the late reply.

> Anyway, doing `\KOMAoption{twoside}{off}`

This is perfect, I didn't know that command! An option directly in the swathesis template would be more prominent, but I don't insist on this and now I don't have to fork this repo. :-)

**Comment by krono** [comment]
great success !

**Comment by LinqLover** [comment]
@krono I noticed that `\KOMAoption{twoside}{off}` on its own does indeed leave inequal margins to the left and the right with a difference of approx. 0.4cm. Is this because of the binding correction?

I tried to turn it off and distribute it to both horizontal margins instead, but somehow the margin do not become larger:

```tex
% disable binding correction in oneside mode, but preserve original \textwidth
\usepackage{xfp}
\makeatletter
\renewcommand*\bindingcorrection[3][1]{%
  % #1 -> "Volume", typically 1
  % #2 -> pages
  % #3 -> grammage
  %
  % Compute the binding correction
  \if@swa@bindingcorrection@set\relax
    \message{^^J Binding correction already set. Ignoring.}
  \else
    \newlength{\tempcorrection}%
    \setlength{\tempcorrection}{\dimexpr \fpeval{0.8 * #2 * #1 * 0.00025 * #3}mm \relax}%
    \message{^^J Binding correction determined as \the\tempcorrection}%
    % Adjust the text width and margins
	\ifcsdef{settypearea}%
      {\csuse{settypearea}{0pt}}%
      {\KOMAoptions{DIV=8,BCOR=0pt}%
       \areaset[current]{\textwidth}{1.61803399\textwidth}}
    \addtolength{\oddsidemargin}{0.5\tempcorrection}%
    \addtolength{\evensidemargin}{0.5\tempcorrection}%
    \@swa@bindingcorrection@settrue
  \fi
}
\makeatother
```

**Comment by krono** [comment]
how does it look if you compile with `\usepackage{showframe}` before `\begin{document}`?
Can you share an image?

**Comment by LinqLover** [comment]
Before:

image

After:

image

(And beyond being useless when reading the document on a screen, the binding correction apparently interferes with my landscape figures, misaligns them and inserts blank pages after them...)

**Comment by krono** [comment]
Well, you can make 0g paper, which is, digital ;D

`\newcommand\papergrammage{0}`

(before `\documentclass`)

**Comment by krono** [comment]
Other than that, look up what `\areaset` is supposed to do in the `scrguide`

**Comment by LinqLover** [comment]
> `\newcommand\papergrammage{0}`

That's smarter than my patch! :D But it still influences the textwidth and leads to the second screenshot above. I would prefer if the binding correction would not influence the layout of my paragraphs and figures... Do I have to add the binding correction width to the width of areaset manually?

**Comment by krono** [comment]
You can also
`\newcommand*\settypearea[1]{}`

**Comment by krono** [comment]
Well; you don't want BCOR, right?
BTW: what does `grep '(typearea)' *.log` say?

**Comment by LinqLover** [comment]
> Well; you don't want BCOR, right?

I do want it for the printed version of my thesis (I have yet to decide whether I will bind it). I don't want it for the online version. I would like to have the same textwidths in both versions. I was surprised that the template seems not to allow me to simply shift the pages to the left and to the right instead of making the next more narrow, if I understand it correctly :D

> BTW: what does `grep '(typearea)' *.log` say?

<table><tr><th>Default grammage</th><th>Zero grammage</th></tr><tr><td><pre><code>(typearea)             DIV  = 10
(typearea)             BCOR = 0.0pt
(typearea)             \paperwidth      = 597.50793pt
(typearea)              \textwidth      = 418.25555pt
(typearea)              DIV departure   = -7%
(typearea)              \evensidemargin = 47.2316pt
(typearea)              \oddsidemargin  = -12.5192pt
(typearea)             \paperheight     = 845.04694pt
(typearea)              \textheight     = 595.80026pt
(typearea)              \topmargin      = -25.16531pt
(typearea)              \headheight     = 17.0pt
(typearea)              \headsep        = 20.40001pt
(typearea)              \topskip        = 11.0pt
(typearea)              \footskip       = 47.6pt
(typearea)              \baselineskip   = 13.6pt
(typearea)              on input line 1743.
(typearea)             DIV  = 10
(typearea)             BCOR = 0.0pt
(typearea)             \paperwidth      = 597.50793pt
(typearea)              \textwidth      = 418.25555pt
(typearea)              DIV departure   = -2%
(typearea)              \evensidemargin = 47.2316pt
(typearea)              \oddsidemargin  = -12.5192pt
(typearea)             \paperheight     = 845.04694pt
(typearea)              \textheight     = 596.48183pt
(typearea)              \topmargin      = -27.03542pt
(typearea)              \headheight     = 17.85005pt
(typearea)              \headsep        = 21.42006pt
(typearea)              \topskip        = 11.0pt
(typearea)              \footskip       = 49.98015pt
(typearea)              \baselineskip   = 14.28004pt
(typearea)              on input line 27.
(typearea)             DIV  = 8
(typearea)             BCOR = 0.0pt
(typearea)             \paperwidth      = 597.50793pt
(typearea)              \textwidth      = 373.44246pt
(typearea)              DIV departure   = 0%
(typearea)              \evensidemargin = 77.107pt
(typearea)              \oddsidemargin  = 2.4185pt
(typearea)             \paperheight     = 845.04694pt
(typearea)              \textheight     = 539.36165pt
(typearea)              \topmargin      = -5.90924pt
(typearea)              \headheight     = 17.85005pt
(typearea)              \headsep        = 21.42006pt
(typearea)              \topskip        = 11.0pt
(typearea)              \footskip       = 49.98015pt
(typearea)              \baselineskip   = 14.28004pt
(typearea)              on input line 112.
(typearea)             DIV  = 8
(typearea)             BCOR = 7.46692pt
(typearea)             \paperwidth      = 597.50793pt
(typearea)              \textwidth      = 368.77563pt
(typearea)              DIV departure   = 2%
(typearea)              \evensidemargin = 75.24026pt
(typearea)              \oddsidemargin  = 8.95206pt
(typearea)             \paperheight     = 845.04694pt
(typearea)              \textheight     = 539.36165pt
(typearea)              \topmargin      = -5.90924pt
(typearea)              \headheight     = 17.85005pt
(typearea)              \headsep        = 21.42006pt
(typearea)              \topskip        = 11.0pt
(typearea)              \footskip       = 49.98015pt
(typearea)              \baselineskip   = 14.28004pt
(typearea)              on input line 112.
(typearea)             DIV  = areaset
(typearea)             BCOR = 7.46692pt
(typearea)             \paperwidth      = 597.50793pt
(typearea)              \textwidth      = 368.77563pt
(typearea)              \evensidemargin = 75.24026pt
(typearea)              \oddsidemargin  = 8.95206pt
(typearea)             \paperheight     = 845.04694pt
(typearea)              \textheight     = 596.68883pt
(typearea)              \topmargin      = -26.85402pt
(typearea)              \headheight     = 15.95pt
(typearea)              \headsep        = 21.42006pt
(typearea)              \topskip        = 11.0pt
(typearea)              \footskip       = 49.98015pt
(typearea)              \baselineskip   = 14.28004pt
(typearea)              on input line 112.</code></pre></td><td><pre><code>(typearea)             DIV  = 10
(typearea)             BCOR = 0.0pt
(typearea)             \paperwidth      = 597.50793pt
(typearea)              \textwidth      = 418.25555pt
(typearea)              DIV departure   = -7%
(typearea)              \evensidemargin = 47.2316pt
(typearea)              \oddsidemargin  = -12.5192pt
(typearea)             \paperheight     = 845.04694pt
(typearea)              \textheight     = 595.80026pt
(typearea)              \topmargin      = -25.16531pt
(typearea)              \headheight     = 17.0pt
(typearea)              \headsep        = 20.40001pt
(typearea)              \topskip        = 11.0pt
(typearea)              \footskip       = 47.6pt
(typearea)              \baselineskip   = 13.6pt
(typearea)              on input line 1743.
(typearea)             DIV  = 10
(typearea)             BCOR = 0.0pt
(typearea)             \paperwidth      = 597.50793pt
(typearea)              \textwidth      = 418.25555pt
(typearea)              DIV departure   = -2%
(typearea)              \evensidemargin = 47.2316pt
(typearea)              \oddsidemargin  = -12.5192pt
(typearea)             \paperheight     = 845.04694pt
(typearea)              \textheight     = 596.48183pt
(typearea)              \topmargin      = -27.03542pt
(typearea)              \headheight     = 17.85005pt
(typearea)              \headsep        = 21.42006pt
(typearea)              \topskip        = 11.0pt
(typearea)              \footskip       = 49.98015pt
(typearea)              \baselineskip   = 14.28004pt
(typearea)              on input line 27.
(typearea)             DIV  = 8
(typearea)             BCOR = 0.0pt
(typearea)             \paperwidth      = 597.50793pt
(typearea)              \textwidth      = 373.44246pt
(typearea)              DIV departure   = 0%
(typearea)              \evensidemargin = 77.107pt
(typearea)              \oddsidemargin  = 2.4185pt
(typearea)             \paperheight     = 845.04694pt
(typearea)              \textheight     = 539.36165pt
(typearea)              \topmargin      = -5.90924pt
(typearea)              \headheight     = 17.85005pt
(typearea)              \headsep        = 21.42006pt
(typearea)              \topskip        = 11.0pt
(typearea)              \footskip       = 49.98015pt
(typearea)              \baselineskip   = 14.28004pt
(typearea)              on input line 112.
(typearea)             DIV  = 8
(typearea)             BCOR = 0.0pt
(typearea)             \paperwidth      = 597.50793pt
(typearea)              \textwidth      = 373.44246pt
(typearea)              DIV departure   = 0%
(typearea)              \evensidemargin = 77.107pt
(typearea)              \oddsidemargin  = 2.4185pt
(typearea)             \paperheight     = 845.04694pt
(typearea)              \textheight     = 539.36165pt
(typearea)              \topmargin      = -5.90924pt
(typearea)              \headheight     = 17.85005pt
(typearea)              \headsep        = 21.42006pt
(typearea)              \topskip        = 11.0pt
(typearea)              \footskip       = 49.98015pt
(typearea)              \baselineskip   = 14.28004pt
(typearea)              on input line 112.
(typearea)             DIV  = areaset
(typearea)             BCOR = 0.0pt
(typearea)             \paperwidth      = 597.50793pt
(typearea)              \textwidth      = 373.44246pt
(typearea)              \evensidemargin = 77.107pt
(typearea)              \oddsidemargin  = 2.4185pt
(typearea)             \paperheight     = 845.04694pt
(typearea)              \textheight     = 604.23987pt
(typearea)              \topmargin      = -29.37103pt
(typearea)              \headheight     = 15.95pt
(typearea)              \headsep        = 21.42006pt
(typearea)              \topskip        = 11.0pt
(typearea)              \footskip       = 49.98015pt
(typearea)              \baselineskip   = 14.28004pt
(typearea)              on input line 112.</code></pre></td></tr></table>

**Comment by LinqLover** [comment]
Wait, does this mean that - even when you want to have a binding correction -, the global text width will become more and more narrow as you continue to add more pages to your thesis? If yes, that means that one should not do any layout polishing before having completed the last page. That is surprising :D Is that a common thing? If yes, maybe this should at least be noted somewhere in the docs or header of this template for unaware writers like me? I think now I understand why I suddenly had to correct new overfull hboxes multiple times in older chapters that I did not even touch again.

If I can trust ChatGPT (which I probably cannot), it would be more common to shift the text away from the binding instead of reducing the width based on the number of pages. Anyway, I'm just documenting my surprise here, I surely do not have a good understanding of professional typography :)

**Comment by krono** [comment]
Yes you are right.
I did not think about that, to be honest, as I have never written lineraly xD

What BCOR does is taking the correction _off the page width_.
And _then_ it calculates the actual layout (ie, margins, and consequentially, text width).
I _then_ change the text height to be in golden ratio with text width.

the idea is: when you have a binding, it _takes away_ visible parts of the page, thus, your page is actually smaller.
and then you apply the calculaiton

**Comment by LinqLover** [comment]
I think I understand it, it still imposes a waterfall process for writers :) For my thesis it does not make any difference anymore, but maybe other users of the template could benefit from a hint in the documentation/a comment in the main tex file about that if you do not want to change this behavior :)

**Comment by krono** [comment]
Am 27. September 2024 04:43:28 MESZ schrieb Christoph Thiede ***@***.***>:
>I think I understand it, it still imposes a waterfall process for writers :) For my thesis it does not make any difference anymore, but maybe other users of the template could benefit from a hint in the documentation/a comment in the main tex file about that if you do not want to change this behavior :)
>

this is the first someone noticed in > 10 years, i think we're good here :)
-- 
Sent from a mobile device

**Comment by LinqLover** [comment]
Or GitHub issues are just the tip of the iceberg :D It doesn't matter for my one anymore though, I've just submitted it ^^

**Comment by krono** [comment]
congrats!

**Comment by LinqLover** [comment]
Thanks! Needless to say it wouldn't have looked the same without your nice template :) https://github.com/LinqLover/semexp-thesis/releases/download/submission/semexp-thesis.pdf

**Pull request closed without merging**
